### ISSUE TITLE
QuakeC source please?

### ISSUE THREAD

**Issue by vittorioromeo** [NightFright2k19/quake_authmdl#2]
I am trying to integrate this fantastic model pack in my [Quake 1 VR project](https://github.com/SuperV1234/Quakespasm-OpenVR/tree/wip_merge_sezero).

In order to implement new features such as controller-based melee attacks and properly set the origin of projectiles and traces, I had to modify the original .qc files. 

It would be really cool if I could do the same with your models, assuming that you are OK with the idea. If so, could you please add the sources to this repo? Cheers

**Comment by NightFright2k19** [comment]
The models were not done by me and the authors did not provide their source files. Maybe it's possible to do what you need by editing the MDL file in QuarK, but I don't know if that editor offers such functions.

**Comment by vittorioromeo** [comment]
Thanks. Do you have any idea how I could contact the authors?

**Comment by NightFright2k19** [comment]
There are many authors involved in this compilation, it will be impossible to get in touch with all of them. Consult the readme to see which models were made by whom. 

Bloodshot, Dwere, osjclatchford, Seven and talisa can still be found in the QuakeOne forums these days, I guess. ijed, Lunaran, Skiffy and Sock are more likely to be encountered in the Func_Msgboard. Capnbubs (who did the Player, Grunt and Rottweiler) hasn't been seen anywhere since many years. I also doubt Orion is still active.
