### ISSUE TITLE
Explosive Boxes with wrong format

### ISSUE THREAD

**Issue by strangebit** [NightFright2k19/quake_authmdl#4]
Just upgraded [Copper](https://github.com/itslunaranyo/copper) to 1.16 and am now getting this warning on E1M1 when using Authentic Model Improvements.

Also posted this on Copper's GitHub: itslunaranyo/copper#3

![spasm0001](https://user-images.githubusercontent.com/11712728/124353823-bf264880-dc00-11eb-92be-145f9514fa70.jpg)

My QuakeSpasm-Spiked revision is f1cc25c0b89580fa72bab61302eb82d28449d8ec (2021-June-25).

**Comment by NightFright2k19** [comment]
I have also been experiencing this issue with Copper and QSS. The problematic BSPs are b_exbox2.bsp and b_explob.bsp. Investigations revealed these are actually MDLs renamed to BSP. That's a pretty ugly hack which Copper (and also other ports) might not like.

Bloodshot made those (they are probably from Quake 1.5). I have sent him a PM on the QuakeOne forums, maybe he is able to make proper BSPs. The error might still be on Copper side though since it apparently uses entity class SOLID_BSP, which requires a .bsp format model. If non-solid class is used, .mdl format would also be tolerated.

Comparison void() misc_explobox:
- misc.qc (Quake): self.solid = SOLID_BBOX; / self.movetype = MOVETYPE_NONE;
- explobox.qc (Copper): self.solid = SOLID_BSP; / self.movetype = MOVETYPE_PUSH;

**Comment by NightFright2k19** [comment]
Exploding boxes have been replaced with true BSPs. This should get rid of the warnings.
