### ISSUE TITLE
Do you know what would be cool?

### ISSUE THREAD

**Issue by yum13241** [NightFright2k19/quake_authmdl#9]
Models for this mission pack: https://quake.fandom.com/wiki/Abyss_of_Pandemonium. (impel)

I know it's a lot to ask for, considering that modeling is hard work.

It would be cool to have these models considering you already bothered with dissolution of eternity and scourge of armagon.

**Comment by yum13241** [comment]
Also, could someone tell my why toggling "Replacement Textures" and " Replacement Models" does nothing? Sometimes I just want to to a quick before/after type of thing, without having to shut the game off, and remove the paks.

**Comment by NightFright2k19** [comment]
We are not going to work on any non-official content. Out of scope, different kind of project. Would it be "cool" to have nicer models in AoP? Sure. Can it be done? In theory yes, but from my side definitely and irreversably not. It was hard enough to get the necessary talents together for this project. They are no longer available.

If you are referring to Quakespasm options: Quake Rerelease uses md5 models while we are using mdl (vanilla Quake format). These models will never work with those menu toggles and I certainly won't change anything about that since it is absolutely pointless. We actually converted some md5 assets over to mdl for our purposes, so we are not going backwards again.

If you want to get that menu toggle working anyway, simply use the md5 models from the Rerelease instead of this. It won't be exactly the same and some assets won't be replaced, but it's close enough.

**Comment by yum13241** [comment]
Make sense.
